### ISSUE TITLE
API Authentication Required

### ISSUE THREAD

**Issue by JBetts97** [JBetts97/ShedApp#1]
<h1>User Authentication</h1>
Need a way for the user to authenticate via the existing API in `/server` directory. <br>
This API should be adapted to use JWT to authenticate when user accesses following protected routes: 

- Dashboard.js -> uses `localhost:8081/items`
- Info.js
- List.js -> uses `localhost:8081/list`

Currently I am using `props.history.push` to push the state returned from `localhost:8081/login` to the dashboard.js, which causes many problems (for example when trying to refresh page, or access page from another page).

**Comment by anikashc** [comment]
So you aren't using any authentication right now? I can try to make an authentication middleware which will use JWT

**Comment by JBetts97** [comment]
> So you aren't using any authentication right now? I can try to make an authentication middleware which will use JWT

Hello @anikashc,
Correct, as of this moment no authentication is being used. JWT middleware would be great!

**Comment by anikashc** [comment]
Okay. Assign it to me. I'll add the middleware along with instructions so as to how to include it in any route you like.

**Comment by JBetts97** [comment]
> Okay. Assign it to me. I'll add the middleware along with instructions so as to how to include it in any route you like.

Thanks @anikashc! Perfect! I have assigned you to this issue.

**Comment by anikashc** [comment]
I am having issues installing the project.

**Comment by JBetts97** [comment]
> I am having issues installing the project.

Hi @anikashc,
I will try to replicate and fix this issue this evening, and will let you know when the fixes are in place.

**Comment by JBetts97** [comment]
Hi @anikashc,
The "docker-compose up" command was not correctly installing the react front-end dependencies. I have resolved this issue by including the react "node_modules" folder locally and mounting them as a volume to the VM in the docker-compose yaml file.

Please could you pull the new changes (git pull), and try the installation again. If you are still facing issues, please kindly provide the error message that you receive.

**Comment by anikashc** [comment]
Still getting this error. I updated by react script etc as well. I can see a node module in the root. But all node modules should be git ignored right? The backend and MySQL is running now. Trying to find a solution. Meanwhile if you could gitignore the node modules, it would be great because anyway I will be doing npm install in root through docker (if it's there)

![image](https://user-images.githubusercontent.com/42690307/110917528-029e3380-8340-11eb-9510-9001106b5aad.png)

**Comment by anikashc** [comment]
Working now but I had to manually do npm install in the client. It would be better if you get rid of all the node modules in the git repo. Now working on the auth

**Comment by anikashc** [comment]
There isn't any package.json file in Server folder. Is it using the one in the root because packages aren't imported

**Comment by JBetts97** [comment]
Hi @anikashc,
I am glad you were able to resolve your installation issue. 👍 

**With regards to the npm packages:**
I have kept all the required node packages in the `/server/node_modules/` folder in the repository. Then when you use the "docker-compose up" command the `docker-compose.yaml` file (line 30) tells docker to mount this `/server/node_modules` folder to `/node_modules` in the container. So if you need to use a new npm package I would locally install it onto your machine using `npm install [package] --save` to save the package to the `/server/node_modules` folder, and then the next time you `docker-compose up` this package should be mounted into the container.

**With regards to .env:**
For the `/server` side I have not yet defined a .env directory. Feel free to create a `.env` file and then use git ignore to prevent pushing the secret to git. Just ensure that in the source code you add a small comment to explain where the .env file will be used.

Thank you for your contribution!

**Comment by anikashc** [comment]
Okay so I am new to docker on the other hand. So if I want to install an npm package, I should install it in the root right where the package.json is there?

**Comment by anikashc** [comment]
I have added the middleware and everything works fine. Haven't added any .env file as there was some issue with the dotenv package. The key is hard coded for now but you can change it to import from .env later. Have added comments for better understanding

**Comment by JBetts97** [comment]
Thanks @anikashc ,
As per your merge request `0b2a86187091983515338fdb8a211973aee7b6cc` I will now close this issue.
I will now begin on changes to the client side to reflect these changes.
